### ISSUE TITLE
Add the Diffie-Hellman Group 1-SHA1 key exchange algorithm and the 3DES-CBC encryption algorithm.

### ISSUE THREAD

**Issue by yangjungis** [honzasp/makiko#7]
Add the Diffie-Hellman Group 1-SHA1 key exchange algorithm and the 3DES-CBC encryption algorithm.

**Comment by yangjungis** [comment]
We need to SSH to some old switch devices

**Comment by honzasp** [comment]
Hi, I added these two algorithms in the latest version 0.2.4. They are quite insecure, so to use them, you will need to enable feature `insecure-crypto` and add the algorithms to your `ClientConfig` (or use [`ClientConfig::default_insecure()`](https://docs.rs/makiko/latest/makiko/struct.ClientConfig.html#method.default_insecure), which enables all  implemented algorithms, including the insecure ones.

Feel free to reopen the issue if you encounter any problems with the new algorithms.
